config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  devise_for :users
  resources :books, only: [:new, :index, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :edit, :update, :show, :create]
  delete 'books/:id' =>'books#destroy', as: 'destroy_book'




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user



  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {  maximum:200 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, uniqueness: true
  validates :name, length: { minimum: 2, maximum:20 }
  validates :introduction, length: { maximum:50 }


  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
 before_action :authenticate_user!, except: [:top, :about]


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

def new
  @book = Book.new
end

def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
if @book.save
  flash[:notice] = "You have created book successfully."
  redirect_to book_path(@book.id)
else
  @books = Book.all
  @user = current_user
  render :index
end
end


def index
  @books = Book.all
  @book = Book.new
  @user = current_user


end

def show
  @book = Book.find(params[:id])
  @user = @book.user
  @books = @user.books
end

def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
  redirect_to book_path(@book.id)
  else
    @books = Book.all
    render :edit
  end
end


def destroy
  @book = Book.find(params[:id])
  @book.destroy
  redirect_to '/books'
end

def edit
  @book = Book.find(params[:id])
  if @book.user == current_user
    render "edit"
  else
    redirect_to books_path
  end
end
end


private
  def book_params
    params.require(:book).permit(:title, :body)
  end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController




  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books



  end


  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)

    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user)
    else
      @users = User.all
      render :edit
    end
  end


  def create
    @user = User.new(user_params)
    @user.user_id = current_user.id
    if @user.save
    redirect_to user_path(@user)
    else
    @users = User.all
    @user = current_user
    render :index
    end
  end




    def index
      @user = User.new
      @users = User.all
      @user = current_user
    end




  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :title, :body)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class=col-md-3>
        <h2>User info</h2>
  <table class="table">
  <tr>


  <% if user.profile_image.attached? %>
    <%= image_tag user.profile_image, size: "100x100" %>
  <% else %>
    <%= image_tag 'no_image', size: "100x100" %>
  <% end %>



  <th>name</th>
  <th><%= user.name %></th>

  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>

  </table>

  <div class="row">
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>

    <i class="fas fa-user-cog"></i>
    <% end %>

  </div>



<h2 class="mt-3">New book</h2>

<%= form_with model: Book.new,url: books_path, method: :post do |f| %>

<div class="form-group">

  <%= f.label :title, "Title" %>
<div class="form-group">
  <%= f.text_field :title %>
</div>


<div class="form-group">

  <%= f.label :body, "Opinion" %>
<div class="form-group">
  <%= f.text_area :body %>
</div>

<div class="form-group">
<div class="action">
  <%= f.submit 'Create Book', class: "btn btn-success" %>
</div>
<% end %>
</div>
</div>
</div>

</div>

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-ig-5 px-5 px-sm-0 mx-auto">



<%= form_with model: @book do |f| %>

<h1>Editing Book</h1>

<div id="error_explanation">

<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

<div class="form-group">
  <h5>Title</h5>
  <%= f.text_field :title %>

<div class="form-group">
  <h5>Opinion</h5>
  <%= f.text_area :body %>

<div class="form-group">
<%= f.submit "Update Book", class: "btn btn-success" %>
<% end %>
</div>

</form>
<%= link_to "Show",book_path(@book.id) %> |
<%= link_to "Back",books_path %>

</div>
</div>
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= render 'list', user: @user %>



  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>

  <table class="table table-hover table-inverse">


  <thead>

    <tr>
      <th></th>
      <th>Title</th>


      <th>Opinion</th>


      <th colspan="3"></th>
    </tr>
  </thead>






    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
    <%= link_to user_path(book.user.id) do %>
    <% if book.user.profile_image.attached? %>
      <%= image_tag book.user.profile_image, size: "100x100" %>
    <% else %>
      <%= image_tag 'no_image', size: "100x100" %>
    <% end %>
    <% end %>

        </td>


      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    <% end %>
      </tr>
    </tbody>
  </div>


 <table class="table table-hover table-inverse"></table>

app/views/books/show.html.erb
<%= render 'list', user: @user %>



<div class="col-md-8 offset-md-1">

  <h2>Book detail</h2>
   <table class="table table-hover table-inverse">


  <table class="table">
    <tbody>
      <tr>

    <td>


    <%= link_to user_path(@user.id) do %>
    <% if @user.profile_image.attached? %>
      <%= image_tag @user.profile_image, size: "100x100" %>
    <% else %>
      <%= image_tag 'no_image', size: "100x100" %>
    <% end %>
    <br>
      <%= link_to @user.name, user_path(@user.id) %>
    <% end %>
    </td>

      <td><%= link_to @book.title, book_path(@book.id) %></td>
      <td><%= @book.body %></td>





    <% if @book.user_id == current_user.id %>
      <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>


      <td><%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>


    <% end %>

      </tr>


    </tbody>
  </table>


  <table class="table table-hover table-inverse"></table>

app/views/homes/about.html.erb
<main>
  <p id="cotice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcom to
        <i class="fas fa-book"></i>
        <strong>Bookers!</strong>
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-x1-6">
        <h1>Welcom to<i class="fas fa-book"></i>
        <strong>Bookers !!</strong>
        </h1>
        <p>In<i class="fas fa-book"></i>
        <strong>Bookers,</strong>
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
        <div class="row"></div>
        <div><%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign-in" %></div>
        <div class="row"></div>
        <div><%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %></div>

      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>

    <title>Bookers2</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<body class="d-flex flex-column vh-100">
  <header class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">


    <%= link_to "Bookers", root_path, class: 'nav-link text-light' %>
        </a>
        <button class="navbar-toggler" type="button" date-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>




      <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
        <i class="fas fa-home"></i>
        Home
        </li>
      <% end %>


      <%= link_to users_path, class: 'nav-link text-light' do %>
        <i class="fas fa-users"></i>
        Users
        </li>
      <% end %>



      <%= link_to books_path, class: 'nav-link text-light' do %>
        <i class="fas fa-book-open"></i>
        Books
        </li>
      <% end %>



      <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
        <i class="fas fa-sign-out-alt"></i>
        Log out
        </li>
      <% end %>


    <% else %>



      <%= link_to root_path, class: "nav-link text-light" do %>
         <i class="fas fa-home"></i>
         Home
         </li>
      <% end %>


      <%= link_to about_path, class: 'nav-link text-light' do %>
        <i class="fas fa-link"></i>
        About
        </li>
      <% end %>


      <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
        <i class="fas fa-user-plus"></i>
        Sign up
        </li>
      <% end %>


      <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
        <i class="fas fa-sign-in-alt"></i>
        Log in
        </li>
      <% end %>

    <% end %>

      </ul>
    </div>
    </div>
    </nav>
  </header>
    <%= flash[:notice] %>
    <%= yield %>
</main>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
</body>
</html>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
       <div class="col-sm-12 col-md-8 col-ig-5 px-5 px-sm-0 mx-auto">

<%= form_with model: @user do |f| %>


    <h1>User info</h1>
  <div id="error_explanation">

<% if @user.errors.any? %>
  <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <div class="form-group">
    <h5>Name</h5>
    <%= f.text_field :name %>

  <div class="form-group">
    <h5>Image</h5>
    <%= f.file_field :profile_image, accept: "image/*" %>


  <div class="form-group">
    <h5>Introduction</h5>
    <%= f.text_area :introduction %>

  <div class="form-group">
    <%= f.submit "Update User", class: "btn btn-secondary" %>
    <% end %>
  </div>
  </form>
</main>

app/views/users/index.html.erb
<%= render 'books/list', user: @user %>


<div class="col-md-8 offset-md-1">
  <h2>Users</h2>



  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
    <td>
    <% if user.profile_image.attached? %>
      <%= image_tag user.profile_image, size: "100x100" %>
    <% else %>
      <%= image_tag 'no_image', size: "100x100" %>
    <% end %>

    </td>
      <td><%= user.name %></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    <% end %>
  </tbody>

  </table>
</div>
  <table class="table table-hover table-inverse"></table>

app/views/users/show.html.erb
<%= render 'books/list', user: @user %>



<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
 <table class="table table-hover table-inverse">

   <thead>

    <tr>
      <th></th>
      <th>Title</th>


      <th>Opinion</th>


      <th colspan="3"></th>
    </tr>
   </thead>






    <tbody>
  <% @books.each do |book| %>
      <tr>
    <td>
  <%= link_to user_path(@user.id) do %>
    <% if @user.profile_image.attached? %>
      <%= image_tag @user.profile_image, size: "100x100" %>
    <% else %>
      <%= image_tag 'no_image', size: "100x100" %>
    <% end %>
    </td>
    <td><%= link_to book.title, book_path(book.id) %></td>
    <td><%= book.body %></td>

  <% end %>
  <% end %>
    </tbody>


 <table class="table table-hover table-inverse"></table>